### ISSUE TITLE
Tattoos of Power

### ISSUE THREAD

**Issue by GregCampbellPresents** [AngelGryph/MadeInHeaven_SpellPack#6] opened 2021-10-14 06:03 UTC
@AngelGryph 
Note: Full screen images gotten via Print Screen turned black.  That's why I used windowed mode to capture screenshots.

Mods Installed: MIH with EET & Worldmap & DLCMerger (and Morpheus's Buff Scripts).

Tattoos of Power has no spell graphic, nor spell description.  Casting it brought up the below screen for me, and the right side of the screen's descriptive text seems like a misplaced string.

(I put Mirror Image and Heroism into Tattoos of Power and it shot Magic Missile at a nearby summoned ooze, turning it hostile!  What?)

![image](https://user-images.githubusercontent.com/52060970/137261499-658bdc53-bcda-4c03-8639-2d06d676fdfd.png)

Also, hovering over the Tattoos of Power ability on the the innate ability bar shows MINOR Sequencer (and still no icon), NOT Tattoos of Power.

![image](https://user-images.githubusercontent.com/52060970/137261373-0a90a8a5-77ab-42c1-a59d-2f0af34d6f6d.png)

**Comment by AngelGryph** [comment] 2021-10-15 23:43
I had actually not intended to include Tattoos of Power with this release at all since it was unfinished, but I forgot to take it out.  Oh well, guess I should go and fix it.  I think I got most of these sorted out, fixes will be in the next release.

**Comment by AngelGryph** [comment] 2021-10-18 00:55
I could not reproduce the spell misfire.  Other issues fixed in v5.

**Closed as completed by AngelGryph** 2021-10-18 00:55 UTC
